# Generated by Django 3.2.6 on 2022-07-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='course',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='courses',
            field=models.CharField(default='No Course Chosen', max_length=100),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='registration_fee',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='registration_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=3),
        ),
    ]
